# Generated by Django 5.2.8 on 2025-11-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("direccion", models.CharField(blank=True, max_length=255, null=True)),
                ("telefono", models.CharField(blank=True, max_length=50, null=True)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("categoria", models.CharField(blank=True, max_length=255, null=True)),
                ("ciudad", models.CharField(blank=True, max_length=100, null=True)),
                ("web", models.CharField(blank=True, max_length=255, null=True)),
                ("fecha_scraping", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
